events {}

http {
    upstream backend_servers {
        server day3-backend1:3000;
        server day3-backend2:3000;
        server day3-backend3:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/myapp.local+3.pem;
        ssl_certificate_key /etc/nginx/certs/myapp.local+3-key.pem;

        location / {
            proxy_pass http://backend_servers;
        }
    }
}