services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

    networks:
      - app_network

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/day2db
    depends_on:
      - mongodb

    networks:
      - app_network

  mongodb:
    image: mongo:8
    volumes:
      - mongo_data:/data/db

    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    name: app_network
    driver: bridge