events {}

http {

    upstream backend_servers {
        server day3-backend1:3000;
        server day3-backend2:3000;
        server day3-backend3:3000;
    }

    server {

        location / {
            proxy_pass http://backend_servers;
        }
    }
}
